/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ir.tamin.infra.ksp.service.kafka.avro;
@org.apache.avro.specific.AvroGenerated
public enum TransactionType implements org.apache.avro.generic.GenericEnumSymbol<TransactionType> {
  DEPOSIT, WITHDRAW  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TransactionType\",\"namespace\":\"ir.tamin.infra.ksp.service.kafka.avro\",\"symbols\":[\"DEPOSIT\",\"WITHDRAW\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
